version: '2.1'

services:
  config-service:
    image: grub/config-service
    container_name: "config-service.compliance-wise.me"
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    restart: always
    ports:
      - "8888:8888"
    expose:
      - "8888"
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  discovery-service:
    image: grub/discovery-service
    container_name: "discovery-service.compliance-wise.me"
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    restart: always
    depends_on:
      config-service:
        condition: service_healthy
    ports:
      - "8761:8761"
    expose:
      - "8761"
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  auth-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      ADMIN_SERVICE_PASSWORD: $ADMIN_SERVICE_PASSWORD
      PARTY_SERVICE_PASSWORD: $PARTY_SERVICE_PASSWORD
    image: grub/auth-service
    restart: always
    depends_on:
      config-service:
        condition: service_healthy
    ports:
      - "5000:5000"
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  auth-mongodb:
    extends:
      service: auth-db-standalone
      file: auth-service/docker-compose.yml
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  api-gateway:
    image: grub/api-gateway
    container_name: "api-gateway.compliance-wise.me"
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    restart: always
    depends_on:
      config-service:
        condition: service_healthy
    ports:
      - "8080:8080"
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  party-db:
    extends:
      service: party-db-standalone
      file: party-service/docker-compose.yml
    ports:
      - "5432:5432"
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  admin-service:
    image: grub/admin-service
    container_name: "admin-service.compliance-wise.me"
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      RDS_HOSTNAME: $RDS_HOSTNAME
      RDS_PORT: $RDS_PORT
      RDS_DB_NAME: $RDS_DB_NAME
      RDS_USERNAME: $RDS_USERNAME
      RDS_PASSWORD: $RDS_PASSWORD
    restart: always
    depends_on:
      config-service:
        condition: service_healthy
    ports:
      - "8001:8001"
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  party-service:
    image: grub/party-service
    container_name: "party-service.compliance-wise.me"
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      RDS_HOSTNAME: $RDS_HOSTNAME
      RDS_PORT: $RDS_PORT
      RDS_DB_NAME: $RDS_DB_NAME
      RDS_USERNAME: $RDS_USERNAME
      RDS_PASSWORD: $RDS_PASSWORD
    restart: always
    depends_on:
      config-service:
        condition: service_healthy
    ports:
      - "8002:8002"
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  monitoring-service:
    image: grub/monitoring-service
    container_name: "monitoring-service.compliance-wise.me"
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    restart: always
    depends_on:
      config-service:
        condition: service_healthy
    ports:
      - "9000:8080"
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  turbine-stream-service:
    image: grub/turbine-stream-service
    container_name: "turbine-stream-service.compliance-wise.me"
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    restart: always
    depends_on:
      config-service:
        condition: service_healthy
    ports:
      - "8989:8989"
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    logging:
      options:
        max-size: "10m"
        max-file: "10"