spring:
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    default-schema: master
  datasource:
    url: jdbc:postgresql://${RDS_HOSTNAME}:${RDS_PORT}/administration
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

security:
  oauth2:
    client:
      clientId: admin-service
      clientSecret: ${ADMIN_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:5000/auth/oauth/token
      grant-type: client_credentials
      scope: server

hibernate:
  connection:
    url: jdbc:postgresql://${RDS_HOSTNAME}:${RDS_PORT}/administration
  multiTenancy: SCHEMA
  multi_tenant_connection_provider: nl.globalorange.compliancewise.core.multitenancy.SchemaMultiTenantConnectionProvider

server:
  port: 8001