spring:
  data:
    mongodb:
      host: admin-mongodb
      username: admin
      password: ${MONGODB_PASSWORD}
      database: admin
      authentication-database: admin
      port: 5002

security:
  oauth2:
    client:
      clientId: admin-service
      clientSecret: ${ADMIN_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:5000/auth/oauth/token
      grant-type: client_credentials
      scope: server

server:
  port: 8001