data:
  rest:
    max-page-size: 50

logging:
  level:
    org.springframework: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

spring:
  rabbitmq:
    host: rabbitmq

security:
  oauth2:
    resource:
      user-info-uri: http://auth-service:5000/auth/users/current