eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:5000/auth/users/current

spring:
  rabbitmq:
    host: localhost
