spring:
  data:
    mongodb:
      host: auth-mongodb
      username: admin
      password: ${MONGODB_PASSWORD}
      database: auth
      authentication-database: auth
      port: 5001

server:
  servlet:
    context-path: /auth
  port: 5000
