spring:
  data:
    rest:
      basePath: '/v1'
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    default-schema: master
  datasource:
    url: jdbc:postgresql://${RDS_HOSTNAME}:${RDS_PORT}/parties
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

hibernate:
  connection:
    url: jdbc:postgresql://${RDS_HOSTNAME}:${RDS_PORT}/parties
  multiTenancy: SCHEMA
  multi_tenant_connection_provider: nl.globalorange.compliancewise.core.multitenancy.SchemaMultiTenantConnectionProvider

server:
  port: 8002